import type { PuzzleDef } from "./types";

// كل بطاقة: عنوان قصير + رسالة سطر واحد للأطفال + إيموجي واضح
export const PUZZLES: PuzzleDef[] = [
  {
    id: "count-animals",
    title: "عُدّ معي",
    description: "كم حيواناً ترى؟",
    emoji: "🐰",
    engine: "counting",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "numbers", label: "الأعداد" }, { key: "attention", label: "التركيز" }],
    color: "bg-primary/15",
    rounds: 6,
  },
  {
    id: "odd-one-out",
    title: "المختلف",
    description: "من لا يشبه الباقي؟",
    emoji: "🔍",
    engine: "odd_one_out",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "logic", label: "المنطق" }, { key: "observation", label: "الملاحظة" }],
    color: "bg-candy/30",
    rounds: 6,
  },
  {
    id: "shape-match",
    title: "الأشكال",
    description: "اختر الشكل نفسه",
    emoji: "🔺",
    engine: "shape_match",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "shapes", label: "الأشكال" }],
    color: "bg-accent/25",
    rounds: 6,
  },
  {
    id: "color-match",
    title: "الألوان",
    description: "اختر اللون الصحيح",
    emoji: "🎨",
    engine: "color_match",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "colors", label: "الألوان" }],
    color: "bg-secondary/50",
    rounds: 6,
  },
  {
    id: "shadow-match",
    title: "ظل من؟",
    description: "خمّن صاحب الظل",
    emoji: "👤",
    engine: "shadow_match",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "observation", label: "الملاحظة" }],
    color: "bg-primary/10",
    rounds: 5,
  },
  {
    id: "letter-picture",
    title: "أول حرف",
    description: "بأي حرف تبدأ؟",
    emoji: "🔤",
    engine: "letter_picture",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "letters", label: "الحروف" }, { key: "reading", label: "القراءة" }],
    color: "bg-candy/25",
    rounds: 6,
  },
  {
    id: "memory-pairs",
    title: "الذاكرة",
    description: "اعثر على الزوج",
    emoji: "🧠",
    engine: "memory_pairs",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "memory", label: "الذاكرة" }, { key: "attention", label: "التركيز" }],
    color: "bg-accent/20",
    rounds: 1,
  },
  {
    id: "pattern-complete",
    title: "أكمل النمط",
    description: "ما التالي؟",
    emoji: "🔁",
    engine: "pattern_complete",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "patterns", label: "الأنماط" }, { key: "logic", label: "المنطق" }],
    color: "bg-primary/15",
    rounds: 6,
  },
  {
    id: "sequence-order",
    title: "الأصغر؟",
    description: "اختر الرقم الأصغر",
    emoji: "🔢",
    engine: "sequence_order",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "numbers", label: "الأعداد" }, { key: "logic", label: "المنطق" }],
    color: "bg-secondary/50",
    rounds: 5,
  },
  {
    id: "missing-piece",
    title: "القطعة الناقصة",
    description: "أكمل الصورة",
    emoji: "🧩",
    engine: "missing_piece",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "observation", label: "الملاحظة" }, { key: "logic", label: "المنطق" }],
    color: "bg-grass/25",
    rounds: 5,
  },
  {
    id: "sorting-category",
    title: "صنّفها",
    description: "أين تنتمي؟",
    emoji: "🗂️",
    engine: "sorting_category",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "classification", label: "التصنيف" }],
    color: "bg-accent/25",
    rounds: 6,
  },
  {
    id: "cause-effect",
    title: "ماذا يحدث؟",
    description: "اختر النتيجة",
    emoji: "💡",
    engine: "cause_effect",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "logic", label: "المنطق" }, { key: "language", label: "اللغة" }],
    color: "bg-candy/30",
    rounds: 5,
  },
  {
    id: "attention-find",
    title: "ابحث جيداً",
    description: "اعثر على الرمز",
    emoji: "👀",
    engine: "attention",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "attention", label: "التركيز" }, { key: "observation", label: "الملاحظة" }],
    color: "bg-primary/15",
    rounds: 5,
  },
  {
    id: "logic-true",
    title: "صح أم خطأ؟",
    description: "فكّر واختر",
    emoji: "✅",
    engine: "logic",
    difficulty: "hard",
    estimatedMinutes: 2,
    skills: [{ key: "logic", label: "المنطق" }],
    color: "bg-grass/25",
    rounds: 6,
  },
  {
    id: "spot-difference",
    title: "اكتشف الفرق",
    description: "أي صورة مختلفة؟",
    emoji: "🔎",
    engine: "spot_difference",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "observation", label: "الملاحظة" }],
    color: "bg-accent/20",
    rounds: 4,
  },
  {
    id: "drag-match",
    title: "وصّل العناصر",
    description: "كلٌّ في مكانه",
    emoji: "🔗",
    engine: "drag_match",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "classification", label: "التصنيف" }, { key: "motor", label: "المهارة الحركية" }],
    color: "bg-secondary/50",
    rounds: 4,
  },
  {
    id: "story-order",
    title: "رتّب القصة",
    description: "أيها أولاً؟",
    emoji: "📖",
    engine: "story_order",
    difficulty: "hard",
    estimatedMinutes: 2,
    skills: [{ key: "language", label: "اللغة" }, { key: "logic", label: "المنطق" }],
    color: "bg-primary/10",
    rounds: 4,
  },
  {
    id: "maze",
    title: "المتاهة",
    description: "اختر الاتجاه",
    emoji: "🌀",
    engine: "maze",
    difficulty: "hard",
    estimatedMinutes: 2,
    skills: [{ key: "spatial", label: "التفكير المكاني" }],
    color: "bg-candy/25",
    rounds: 3,
  },
  {
    id: "audio-recognition",
    title: "اسمع واختر",
    description: "ميّز الصوت",
    emoji: "🔊",
    engine: "audio_recognition",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "listening", label: "السمع" }, { key: "language", label: "اللغة" }],
    color: "bg-accent/25",
    rounds: 5,
  },
  {
    id: "jigsaw-rotate",
    title: "الاتجاه الصحيح",
    description: "أيها معتدل؟",
    emoji: "🧩",
    engine: "jigsaw_rotate",
    difficulty: "hard",
    estimatedMinutes: 2,
    skills: [{ key: "spatial", label: "التفكير المكاني" }, { key: "motor", label: "المهارة الحركية" }],
    color: "bg-grass/25",
    rounds: 3,
  },
  {
    id: "daily-mini",
    title: "تحدّي اليوم",
    description: "لغز سريع كل يوم",
    emoji: "🌟",
    engine: "daily_mini",
    difficulty: "easy",
    estimatedMinutes: 1,
    skills: [{ key: "mix", label: "متنوع" }],
    color: "bg-primary/20",
    rounds: 3,
  },
];

export function getPuzzleById(id: string): PuzzleDef | undefined {
  return PUZZLES.find((p) => p.id === id);
}
