import type { PuzzleDef } from "./types";

export const PUZZLES: PuzzleDef[] = [
  {
    id: "count-animals",
    title: "عُدّ الحيوانات",
    description: "أحصِ الحيوانات في الصورة واختر العدد الصحيح",
    emoji: "🐰",
    engine: "counting",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "numbers", label: "الأعداد" }, { key: "attention", label: "التركيز" }],
    color: "bg-primary/15",
    rounds: 6,
  },
  {
    id: "odd-one-out",
    title: "المختلف",
    description: "اعثر على العنصر المختلف بين المجموعة",
    emoji: "🔍",
    engine: "odd_one_out",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "logic", label: "المنطق" }, { key: "observation", label: "الملاحظة" }],
    color: "bg-candy/30",
    rounds: 6,
  },
  {
    id: "shape-match",
    title: "طابق الأشكال",
    description: "اختر الشكل المطابق للنموذج",
    emoji: "🔺",
    engine: "shape_match",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "shapes", label: "الأشكال" }],
    color: "bg-accent/25",
    rounds: 6,
  },
  {
    id: "color-match",
    title: "طابق الألوان",
    description: "اختر اللون المطلوب من بين الخيارات",
    emoji: "🎨",
    engine: "color_match",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "colors", label: "الألوان" }],
    color: "bg-secondary/50",
    rounds: 6,
  },
  {
    id: "shadow-match",
    title: "ظل من؟",
    description: "صل الكائن بالظل المطابق له",
    emoji: "👤",
    engine: "shadow_match",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "observation", label: "الملاحظة" }],
    color: "bg-primary/10",
    rounds: 5,
  },
  {
    id: "letter-picture",
    title: "الحرف والصورة",
    description: "اختر الحرف الذي تبدأ به الكلمة",
    emoji: "أ",
    engine: "letter_picture",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "letters", label: "الحروف" }, { key: "reading", label: "القراءة" }],
    color: "bg-candy/25",
    rounds: 6,
  },
  {
    id: "memory-pairs",
    title: "ذاكرة الأزواج",
    description: "اقلب البطاقات وابحث عن الزوج المتطابق",
    emoji: "🧠",
    engine: "memory_pairs",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "memory", label: "الذاكرة" }, { key: "attention", label: "التركيز" }],
    color: "bg-accent/20",
    rounds: 1,
  },
  {
    id: "pattern-complete",
    title: "أكمل النمط",
    description: "اختر العنصر الذي يكمل النمط",
    emoji: "🔁",
    engine: "pattern_complete",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "patterns", label: "الأنماط" }, { key: "logic", label: "المنطق" }],
    color: "bg-primary/15",
    rounds: 6,
  },
  {
    id: "sequence-order",
    title: "رتّب الأرقام",
    description: "رتّب الأرقام من الأصغر إلى الأكبر",
    emoji: "🔢",
    engine: "sequence_order",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "numbers", label: "الأعداد" }, { key: "logic", label: "المنطق" }],
    color: "bg-secondary/50",
    rounds: 5,
  },
  {
    id: "missing-piece",
    title: "القطعة الناقصة",
    description: "اختر القطعة المناسبة لإكمال الصورة",
    emoji: "🧩",
    engine: "missing_piece",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "observation", label: "الملاحظة" }, { key: "logic", label: "المنطق" }],
    color: "bg-grass/25",
    rounds: 5,
  },
  {
    id: "sorting-category",
    title: "صنّف حسب النوع",
    description: "اختر الكائن الذي ينتمي للمجموعة",
    emoji: "🗂️",
    engine: "sorting_category",
    difficulty: "easy",
    estimatedMinutes: 2,
    skills: [{ key: "classification", label: "التصنيف" }],
    color: "bg-accent/25",
    rounds: 6,
  },
  {
    id: "cause-effect",
    title: "السبب والنتيجة",
    description: "اختر النتيجة المناسبة للحدث",
    emoji: "💡",
    engine: "cause_effect",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "logic", label: "المنطق" }, { key: "language", label: "اللغة" }],
    color: "bg-candy/30",
    rounds: 5,
  },
  {
    id: "attention-find",
    title: "تحدّي التركيز",
    description: "اعثر على الرمز المطلوب وسط الفوضى",
    emoji: "👀",
    engine: "attention",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "attention", label: "التركيز" }, { key: "observation", label: "الملاحظة" }],
    color: "bg-primary/15",
    rounds: 5,
  },
  {
    id: "logic-true",
    title: "صح أم خطأ؟",
    description: "اختر الإجابة المنطقية الصحيحة",
    emoji: "✅",
    engine: "logic",
    difficulty: "hard",
    estimatedMinutes: 2,
    skills: [{ key: "logic", label: "المنطق" }],
    color: "bg-grass/25",
    rounds: 6,
  },
  {
    id: "spot-difference",
    title: "اكتشف الفرق",
    description: "ابحث عن الاختلاف بين الصورتين",
    emoji: "🔎",
    engine: "spot_difference",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "observation", label: "الملاحظة" }],
    color: "bg-accent/20",
    rounds: 4,
  },
  {
    id: "drag-match",
    title: "صل العنصر بمكانه",
    description: "اسحب كل صورة إلى الفئة الصحيحة",
    emoji: "🔗",
    engine: "drag_match",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "classification", label: "التصنيف" }, { key: "motor", label: "المهارة الحركية" }],
    color: "bg-secondary/50",
    rounds: 4,
  },
  {
    id: "story-order",
    title: "رتّب القصة",
    description: "رتّب أحداث القصة بالترتيب الصحيح",
    emoji: "📖",
    engine: "story_order",
    difficulty: "hard",
    estimatedMinutes: 2,
    skills: [{ key: "language", label: "اللغة" }, { key: "logic", label: "المنطق" }],
    color: "bg-primary/10",
    rounds: 4,
  },
  {
    id: "maze",
    title: "المتاهة",
    description: "ساعد الشخصية على الوصول إلى الهدف",
    emoji: "🌀",
    engine: "maze",
    difficulty: "hard",
    estimatedMinutes: 2,
    skills: [{ key: "spatial", label: "التفكير المكاني" }],
    color: "bg-candy/25",
    rounds: 3,
  },
  {
    id: "audio-recognition",
    title: "ميّز الصوت",
    description: "استمع واختر الكلمة الصحيحة",
    emoji: "🔊",
    engine: "audio_recognition",
    difficulty: "medium",
    estimatedMinutes: 2,
    skills: [{ key: "listening", label: "السمع" }, { key: "language", label: "اللغة" }],
    color: "bg-accent/25",
    rounds: 5,
  },
  {
    id: "jigsaw-rotate",
    title: "أعد تركيب الصورة",
    description: "دوّر القطع لتعود الصورة كاملة",
    emoji: "🧩",
    engine: "jigsaw_rotate",
    difficulty: "hard",
    estimatedMinutes: 2,
    skills: [{ key: "spatial", label: "التفكير المكاني" }, { key: "motor", label: "المهارة الحركية" }],
    color: "bg-grass/25",
    rounds: 3,
  },
  {
    id: "daily-mini",
    title: "تحدّي اليوم",
    description: "لغز يومي صغير يجمع بين عدة مهارات",
    emoji: "🌟",
    engine: "daily_mini",
    difficulty: "easy",
    estimatedMinutes: 1,
    skills: [{ key: "mix", label: "متنوع" }],
    color: "bg-primary/20",
    rounds: 3,
  },
];

export function getPuzzleById(id: string): PuzzleDef | undefined {
  return PUZZLES.find((p) => p.id === id);
}
