/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as PuzzlesIdRouteImport } from './routes/puzzles.$id'
import { Route as AuthenticatedMyOrdersRouteImport } from './routes/_authenticated.my-orders'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated.checkout'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedStoryOrderIdRouteImport } from './routes/_authenticated.story.$orderId'
import { Route as AuthenticatedOrderTemplateIdRouteImport } from './routes/_authenticated.order.$templateId'

const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesIdRoute = PuzzlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PuzzlesRoute,
} as any)
const AuthenticatedMyOrdersRoute = AuthenticatedMyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoryOrderIdRoute =
  AuthenticatedStoryOrderIdRouteImport.update({
    id: '/story/$orderId',
    path: '/story/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrderTemplateIdRoute =
  AuthenticatedOrderTemplateIdRouteImport.update({
    id: '/order/$templateId',
    path: '/order/$templateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/cart': typeof CartRoute
  '/create': typeof CreateRoute
  '/games': typeof GamesRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/my-orders': typeof AuthenticatedMyOrdersRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/stories/': typeof StoriesIndexRoute
  '/order/$templateId': typeof AuthenticatedOrderTemplateIdRoute
  '/story/$orderId': typeof AuthenticatedStoryOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/cart': typeof CartRoute
  '/create': typeof CreateRoute
  '/games': typeof GamesRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/my-orders': typeof AuthenticatedMyOrdersRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/stories': typeof StoriesIndexRoute
  '/order/$templateId': typeof AuthenticatedOrderTemplateIdRoute
  '/story/$orderId': typeof AuthenticatedStoryOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/cart': typeof CartRoute
  '/create': typeof CreateRoute
  '/games': typeof GamesRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/my-orders': typeof AuthenticatedMyOrdersRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/stories/': typeof StoriesIndexRoute
  '/_authenticated/order/$templateId': typeof AuthenticatedOrderTemplateIdRoute
  '/_authenticated/story/$orderId': typeof AuthenticatedStoryOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/books'
    | '/cart'
    | '/create'
    | '/games'
    | '/puzzles'
    | '/admin'
    | '/checkout'
    | '/my-orders'
    | '/puzzles/$id'
    | '/stories/$slug'
    | '/stories/'
    | '/order/$templateId'
    | '/story/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/books'
    | '/cart'
    | '/create'
    | '/games'
    | '/puzzles'
    | '/admin'
    | '/checkout'
    | '/my-orders'
    | '/puzzles/$id'
    | '/stories/$slug'
    | '/stories'
    | '/order/$templateId'
    | '/story/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/books'
    | '/cart'
    | '/create'
    | '/games'
    | '/puzzles'
    | '/_authenticated/admin'
    | '/_authenticated/checkout'
    | '/_authenticated/my-orders'
    | '/puzzles/$id'
    | '/stories/$slug'
    | '/stories/'
    | '/_authenticated/order/$templateId'
    | '/_authenticated/story/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BooksRoute: typeof BooksRoute
  CartRoute: typeof CartRoute
  CreateRoute: typeof CreateRoute
  GamesRoute: typeof GamesRoute
  PuzzlesRoute: typeof PuzzlesRouteWithChildren
  StoriesSlugRoute: typeof StoriesSlugRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/$id': {
      id: '/puzzles/$id'
      path: '/$id'
      fullPath: '/puzzles/$id'
      preLoaderRoute: typeof PuzzlesIdRouteImport
      parentRoute: typeof PuzzlesRoute
    }
    '/_authenticated/my-orders': {
      id: '/_authenticated/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof AuthenticatedMyOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/story/$orderId': {
      id: '/_authenticated/story/$orderId'
      path: '/story/$orderId'
      fullPath: '/story/$orderId'
      preLoaderRoute: typeof AuthenticatedStoryOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/order/$templateId': {
      id: '/_authenticated/order/$templateId'
      path: '/order/$templateId'
      fullPath: '/order/$templateId'
      preLoaderRoute: typeof AuthenticatedOrderTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedMyOrdersRoute: typeof AuthenticatedMyOrdersRoute
  AuthenticatedOrderTemplateIdRoute: typeof AuthenticatedOrderTemplateIdRoute
  AuthenticatedStoryOrderIdRoute: typeof AuthenticatedStoryOrderIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedMyOrdersRoute: AuthenticatedMyOrdersRoute,
  AuthenticatedOrderTemplateIdRoute: AuthenticatedOrderTemplateIdRoute,
  AuthenticatedStoryOrderIdRoute: AuthenticatedStoryOrderIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PuzzlesRouteChildren {
  PuzzlesIdRoute: typeof PuzzlesIdRoute
}

const PuzzlesRouteChildren: PuzzlesRouteChildren = {
  PuzzlesIdRoute: PuzzlesIdRoute,
}

const PuzzlesRouteWithChildren =
  PuzzlesRoute._addFileChildren(PuzzlesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BooksRoute: BooksRoute,
  CartRoute: CartRoute,
  CreateRoute: CreateRoute,
  GamesRoute: GamesRoute,
  PuzzlesRoute: PuzzlesRouteWithChildren,
  StoriesSlugRoute: StoriesSlugRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
